### PR TITLE
Update AlertView

### PR DESCRIPTION
**Pull request by ghost**
Border and Opacity

### CODE REVIEW

**Comment by mtonio91** [comment]
Why set a different opacity and a border ? I don't think that's relevant for the controller.

**Comment by ghost** [comment]
Add a bit of styling to the controller

**Comment by ghost** [comment]
Should I rather add it to one of the demos?

**Comment by mtonio91** [comment]
This is hard coded setups. If it is a customization feature (I mean let the user the choice to change himself the controller apparence) I'll merge the pull request. :) like I did for the title ant text message font customization.

**Comment by ghost** [comment]
Awesome thanks for merging.

**Pull request closed without merging**
